//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFlixr.Data.Scraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempData
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public byte Type { get; set; }
        public bool Skip { get; set; }
    }
}
