//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFlixr.Data.Scraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int Id { get; set; }
        public string MovieUrl { get; set; }
        public int Duration { get; set; }
        public string Title { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string Uploader { get; set; }
        public byte Source { get; set; }
        public string VideoId { get; set; }
        public byte Type { get; set; }
        public string Url { get; set; }
    }
}
