//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFlixr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carousel
    {
        public Carousel()
        {
            this.CaroselItems = new HashSet<CaroselItem>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleLink { get; set; }
        public byte Language { get; set; }
        public byte Category { get; set; }
        public byte Type { get; set; }
        public byte Size { get; set; }
        public byte Rows { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<CaroselItem> CaroselItems { get; set; }
    }
}
