//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFlixr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie : Show
    {
        public System.DateTime ReleaseData { get; set; }
        public string DirectedBy { get; set; }
        public string ProducedBy { get; set; }
        public string WrittenBy { get; set; }
        public string Starring { get; set; }
        public string MusicBy { get; set; }
        public string SongsBy { get; set; }
        public string CinematographyBy { get; set; }
        public string EditingBy { get; set; }
        public string Studio { get; set; }
        public string DistributedBy { get; set; }
        public string ScreenplayBy { get; set; }
        public short RunningTime { get; set; }
    }
}
