//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFlixr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show
    {
        public Show()
        {
            this.Children = new HashSet<Show>();
            this.VideoLinks = new HashSet<VideoLink>();
            this.Images = new HashSet<Image>();
            this.CaroselItems = new HashSet<CaroselItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Title { get; set; }
        public byte Type { get; set; }
        public string UniqueToken { get; set; }
        public byte Language { get; set; }
        public short Year { get; set; }
        public byte Country { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Show> Children { get; set; }
        public virtual Show Parent { get; set; }
        public virtual ICollection<VideoLink> VideoLinks { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<CaroselItem> CaroselItems { get; set; }
    }
}
