//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFlixr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoLink
    {
        public int Id { get; set; }
        public int ShowId { get; set; }
        public string UniqueToken { get; set; }
        public string Url { get; set; }
        public int IndexNumber { get; set; }
        public int Sequence { get; set; }
        public int Duration { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string Title { get; set; }
        public string Uploader { get; set; }
        public byte Source { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
